### ISSUE TITLE
Cost of each pair of neigbors?

### ISSUE THREAD

**Issue by ddrm86** [udacity/isdc-router-planner-project#1]
Hello. I am trying to pass the "Implement Route Planner" (an implementation of A* in a graph) in order to be a reviewer of that project. The thing is, neither the notebook nor the Map object specify a cost function for each pair of neighbors. Since we are given the x and y coordinates of every intersection and the maps are visualized with straight roads joining every intersection, I assumed that the cost is the euclidean distance.
But, one of my test cases is apparently wrong: 

    For start: 8 Goal: 24 Your path: [8, 14, 16, 37, 12, 17, 10, 24] Correct:   [8, 30, 16, 37, 12, 17, 10, 24]
    You passed 2 / 3 test cases

If I calculate the partial distances of each solution:

    from math import sqrt
    def euc2d_dist(M, a, b):
        ax, ay = M.intersections[a]
        bx, by = M.intersections[b]
        return sqrt((ax-bx)**2 + (ay-by)**2)

    def part_dist(inter):
        p_sum = 0
        p_dist = []
        for i in range(len(inter)-1):
            p_sum += euc2d_dist(map_40, inter[i], inter[i+1])
            p_dist.append(p_sum)
        return p_dist

the results are:

    In [40]:
    part_dist([8, 14, 16, 37, 12, 17, 10, 24])
    Out[40]:
    [0.220752785727394,
     0.3521236384615354,
     0.5599055134778331,
     0.7743886259711613,
     0.9616909257792738,
     1.1554435348554717,
     1.3648778867109002]

    In [41]:
    part_dist([8, 30, 16, 37, 12, 17, 10, 24])
    Out[41]:
    [0.18317798749706926,
     0.43127317334825066,
     0.6390550483645484,
     0.8535381608578766,
     1.0408404606659891,
     1.234593069742187,
     1.4440274215976152]

It looks like my solution is better (assuming euclidean distance).
I would like some clarification about this.
Thank you very much.

**Comment by ddrm86** [comment]
Totally forgot about the show_map function... here is my solution versus the test case solution:

![captura de pantalla 2017-11-14 14 25 06](https://user-images.githubusercontent.com/15799167/32782190-ea40f76a-c947-11e7-935d-964a5e1aea39.png)

**Comment by rishabhc6499** [comment]
what is inter?

**Comment by mvirgo** [comment]
Closing this out based on age of issue + the project having since been updated to something different. I don't see any particular error in what you've posted, although it may have been in a different portion of your algorithm.
